channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - ruamel.yaml=0.17.21
  - numpy=1.22.4
  - pytorch::pytorch=1.11.0
  - cudatoolkit=11.5.1
  - pytorch::torchvision=0.12.0
#  - pytorch-lightning=1.6.3
  - transformers=4.19.2
  - wandb==0.12.17
  - scikit-learn=1.1.1
  - pandas=1.4.2
  - openpyxl=3.0.9
  - matplotlib=3.5.2
  - nibabel=3.2.2

  # work around for: https://github.com/SimpleITK/SimpleITK/issues/1433, waiting for ITK 5.3
  - SimpleITK::SimpleITK=2.0.2

  - pip=22.1.1
  - pip:
    - pytorch-lightning==1.6.4
    - itk==5.2.1.post1
    - evalutils==0.3.1
    - git+https://github.com/JoHof/lungmask
    - -e third-party/MONAI[einops]  # einops for ViT
    - -e third-party/nnUNet
