channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - ruamel.yaml
  - numpy
  - einops
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda=11.7
  - timm
  - wandb
  - scikit-learn
  - pandas
  - openpyxl
  - matplotlib
  - nibabel
  - simpleitk

  - pip
  - pip:
    - itk
    - evalutils
    - pytorch-lightning
    - lightning-bolts
    - torchmetrics
    - lightning-bolts
    - transformers
#    - git+https://github.com/JoHof/lungmask
    - -e third-party/MONAI
    - -e third-party/nnUNet
