channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - ruamel.yaml=0.17.21
  - numpy=1.23.1
  - pytorch::pytorch=1.12.0
  - cudatoolkit=11.6
  - pytorch::torchvision=0.13.0
  - pytorch-lightning=1.6.5
  - torchmetrics=0.9.2
  - transformers=4.20.1
  - wandb=0.12.21
  - scikit-learn=1.1.1
  - pandas=1.4.3
  - openpyxl=3.0.9
  - matplotlib=3.5.2
  - nibabel=4.0.1

  # work around for: https://github.com/SimpleITK/SimpleITK/issues/1433, waiting for ITK 5.3
  - SimpleITK::SimpleITK=2.0.2

  - pip=22.1.2
  - pip:
    - itk==5.2.1.post1
    - evalutils==0.3.1
#    - git+https://github.com/JoHof/lungmask
    - -e third-party/MONAI[einops]  # einops for ViT
    - -e third-party/nnUNet
